"""Deterministic DSP analysis contracts through CODE V8-0B."""

from .envelope import analyze_envelope
from .beating import BeatingAnalysis, analyze_beating
from .complexity import ComplexityAnalysis, analyze_complexity
from .frequency_modulation import (
    FrequencyModulationAnalysis,
    FrequencyModulationFrame,
    analyze_frequency_modulation,
)
from .regions import (
    InterestRegion,
    RegionInterestAnalysis,
    RegionKind,
    RegionSlotAllocation,
    allocate_region_slots,
    analyze_region_interest,
)
from .saturation import (
    SaturationAnalysis,
    SaturationFrameAnalysis,
    analyze_saturation,
)
from .levels import analyze_levels
from .models import (
    ChangePointEvent,
    EnvelopeAnalysis,
    LevelAnalysis,
    NoiseAnalysis,
    NoiseClass,
    NoiseFrameAnalysis,
    PeriodicityClass,
    PhaseContinuityClass,
    PhaseFrameAnalysis,
    PhaseMotionAnalysis,
    PhaseTransitionAnalysis,
    PitchMotionClass,
    PitchFrameAnalysis,
    PitchPeriodicityAnalysis,
    TimeDomainAnalysis,
    TransientChangeAnalysis,
    TransientChangeClass,
    TransientEvent,
    TransientFrameAnalysis,
)
from .noise import analyze_audio_source_noise, analyze_noise
from .periodicity import analyze_audio_source_pitch_periodicity, analyze_pitch_periodicity
from .phase_motion import analyze_audio_source_phase_motion, analyze_phase_motion
from .pitch import (
    describe_frequency,
    frequency_to_midi,
    midi_note_name,
    midi_to_frequency,
    nearest_midi_note,
)
from .pitch_candidates import (
    WorkingPitchCandidate,
    WorkingPitchCandidateKind,
    WorkingPitchCandidates,
    generate_working_pitch_candidates,
)
from .repitch import (
    WorkingPitchDecision,
    WorkingPitchPlan,
    WorkingPitchPolicy,
    analyze_audio_source_working_pitch,
    plan_working_pitch,
)
from .segmentation import (
    AttackDecision,
    AttackPolicy,
    SegmentKind,
    SegmentationAnalysis,
    SourceSegment,
    analyze_audio_source_segmentation,
    segment_source,
)
from .cycle_detection import (
    CycleCandidate,
    CycleCandidateStatus,
    CycleDiscoveryAnalysis,
    analyze_audio_source_cycles,
    discover_cycles,
)
from .cycle_selection import (
    CycleSelectionDecision,
    CycleSelectionPolicy,
    RankedCycleCandidate,
    SelectedCycleSet,
    analyze_audio_source_cycle_selection,
    select_representative_cycles,
)
from .reconstruction import (
    ReconstructionDecision,
    ReconstructionStrategy,
    ReconstructedWave,
    ReconstructedWaveSet,
    analyze_audio_source_reconstruction,
    reconstruct_selected_cycles,
)
from .signal import (
    SignalAnalysis,
    SignalExtensionAnalysis,
    analyze_audio_source_signal,
    analyze_audio_source_signal_extensions,
    analyze_signal,
    analyze_signal_extensions,
)
from .classification import (
    ClassificationFeature,
    SourceClass,
    SourceClassScore,
    SourceClassification,
    classify_source,
)
from .decisions import (
    DecisionStatus,
    EngineeringDecision,
    EngineeringRecommendation,
    RecommendationCode,
    RecommendationPriority,
    decide_wavetable_readiness,
)
from .code_v5 import (
    CodeV5Analysis,
    analyze_audio_source_code_v5,
    assemble_code_v5_analysis,
)
from .code_v6 import (
    CodeV6Analysis,
    analyze_audio_source_code_v6,
    assemble_code_v6_analysis,
)
from .harmonic_perceptual import (
    HarmonicPeak,
    HarmonicPerceptualAnalysis,
    analyze_audio_source_harmonic_perceptual,
    analyze_harmonic_perceptual,
)
from .spectral import (
    SpectralAnalysis,
    SpectralFrameAnalysis,
    analyze_audio_source_spectral,
    analyze_spectral,
)
from .time_domain import analyze_audio_source, analyze_time_domain
from .transients import analyze_audio_source_transients, analyze_transients

__all__ = [
    "ChangePointEvent",
    "SignalExtensionAnalysis",
    "SaturationFrameAnalysis",
    "SaturationAnalysis",
    "RegionSlotAllocation",
    "RegionKind",
    "RegionInterestAnalysis",
    "InterestRegion",
    "FrequencyModulationFrame",
    "FrequencyModulationAnalysis",
    "ComplexityAnalysis",
    "BeatingAnalysis",
    "ClassificationFeature",
    "CodeV5Analysis",
    "CodeV6Analysis",
    "DecisionStatus",
    "EngineeringDecision",
    "EngineeringRecommendation",
    "EnvelopeAnalysis",
    "HarmonicPeak",
    "HarmonicPerceptualAnalysis",
    "LevelAnalysis",
    "NoiseAnalysis",
    "NoiseClass",
    "NoiseFrameAnalysis",
    "PeriodicityClass",
    "PhaseContinuityClass",
    "PhaseFrameAnalysis",
    "PhaseMotionAnalysis",
    "PhaseTransitionAnalysis",
    "PitchMotionClass",
    "PitchFrameAnalysis",
    "PitchPeriodicityAnalysis",
    "WorkingPitchCandidate",
    "WorkingPitchCandidateKind",
    "WorkingPitchCandidates",
    "WorkingPitchDecision",
    "WorkingPitchPlan",
    "WorkingPitchPolicy",
    "AttackDecision",
    "AttackPolicy",
    "SegmentKind",
    "SegmentationAnalysis",
    "SourceSegment",
    "CycleCandidate",
    "CycleCandidateStatus",
    "CycleDiscoveryAnalysis",
    "CycleSelectionDecision",
    "CycleSelectionPolicy",
    "RankedCycleCandidate",
    "SelectedCycleSet",
    "ReconstructionDecision",
    "ReconstructionStrategy",
    "ReconstructedWave",
    "ReconstructedWaveSet",
    "SignalAnalysis",
    "SourceClass",
    "SourceClassScore",
    "SourceClassification",
    "RecommendationCode",
    "RecommendationPriority",
    "SpectralAnalysis",
    "SpectralFrameAnalysis",
    "TimeDomainAnalysis",
    "TransientChangeAnalysis",
    "TransientChangeClass",
    "TransientEvent",
    "TransientFrameAnalysis",
    "analyze_audio_source",
    "analyze_signal_extensions",
    "analyze_saturation",
    "analyze_region_interest",
    "analyze_frequency_modulation",
    "analyze_complexity",
    "analyze_beating",
    "analyze_audio_source_signal_extensions",
    "allocate_region_slots",
    "analyze_audio_source_code_v5",
    "analyze_audio_source_code_v6",
    "analyze_audio_source_harmonic_perceptual",
    "analyze_audio_source_signal",
    "analyze_audio_source_noise",
    "analyze_audio_source_phase_motion",
    "analyze_audio_source_pitch_periodicity",
    "analyze_audio_source_transients",
    "analyze_audio_source_working_pitch",
    "analyze_audio_source_segmentation",
    "analyze_audio_source_cycles",
    "analyze_audio_source_cycle_selection",
    "analyze_audio_source_reconstruction",
    "analyze_envelope",
    "analyze_levels",
    "analyze_noise",
    "analyze_phase_motion",
    "analyze_pitch_periodicity",
    "generate_working_pitch_candidates",
    "plan_working_pitch",
    "segment_source",
    "discover_cycles",
    "select_representative_cycles",
    "reconstruct_selected_cycles",
    "analyze_signal",
    "assemble_code_v5_analysis",
    "assemble_code_v6_analysis",
    "classify_source",
    "decide_wavetable_readiness",
    "analyze_harmonic_perceptual",
    "analyze_spectral",
    "analyze_audio_source_spectral",
    "analyze_time_domain",
    "analyze_transients",
    "describe_frequency",
    "frequency_to_midi",
    "midi_note_name",
    "midi_to_frequency",
    "nearest_midi_note",
]
