"""Public API for W-MWXT-WAVETABLE-TOOL."""

from .allocation import UserWaveAllocation, allocate_user_waves
from .analysis import (
    EnvelopeAnalysis,
    LevelAnalysis,
    PeriodicityClass,
    PitchFrameAnalysis,
    PitchPeriodicityAnalysis,
    TimeDomainAnalysis,
    analyze_audio_source,
    analyze_audio_source_pitch_periodicity,
    analyze_envelope,
    analyze_levels,
    analyze_pitch_periodicity,
    analyze_time_domain,
    describe_frequency,
    frequency_to_midi,
    midi_note_name,
    midi_to_frequency,
    nearest_midi_note,
)
from .audio import (
    AudioContainerFormat,
    AudioMeasurements,
    AudioMetadata,
    AudioSource,
    InvalidSamplePolicy,
    MonoConversionReport,
    MonoPolicy,
    MonoStrategy,
    convert_to_mono,
    fingerprint_file,
    import_audio,
    measure_mono,
    normalize_float_samples,
    supported_extensions,
)
from .constants import DumpType
from .destinations import (
    DeviceAddress,
    SoundBank,
    SoundDestination,
    SoundNamePolicy,
    UserWavetableDestination,
    encode_sound_name,
)
from .dump import DumpFile, split_sysex_stream
from .hardware_test import (
    HardwareTestBuild,
    HardwareTestBuildOutputPaths,
    build_hardware_test_from_backup,
)
from .hardware_validation import (
    ComparisonStatus,
    HardwarePackageProfile,
    HardwarePreparation,
    HardwarePreflightReport,
    HardwareReadbackReport,
    HardwareReadbackResult,
    HardwareValidationStatus,
    compare_hardware_readback,
    inspect_hardware_package,
    prepare_hardware_validation,
)
from .identity import IdentityReply
from .manifest import PackageManifest
from .message import SysExMessage
from .models import (
    GlobalParameters,
    MultiProgram,
    SoundProgram,
    UserWave,
    UserWavetable,
    decode_typed,
)
from .package import (
    PackageBuildResult,
    PackageOutputPaths,
    PackagePlan,
    PackageRequest,
    build_package,
    plan_package,
)
from .project import (
    MinimalProject,
    MinimalProjectManifest,
    ProjectAudioRecord,
    ProjectSaveResult,
    ProjectSourceCheck,
    SourceStatus,
    SourceValidationPolicy,
    open_project,
    save_project,
)
from .version import __version__
from .safety import (
    CollisionReport,
    MemoryTarget,
    MemoryTargetKind,
    OverwritePlan,
    analyze_collisions,
)


__all__ = [
    "AudioContainerFormat",
    "AudioMeasurements",
    "AudioMetadata",
    "AudioSource",
    "ComparisonStatus",
    "CollisionReport",
    "DeviceAddress",
    "DumpFile",
    "DumpType",
    "GlobalParameters",
    "TimeDomainAnalysis",
    "LevelAnalysis",
    "EnvelopeAnalysis",
    "PitchFrameAnalysis",
    "PitchPeriodicityAnalysis",
    "PeriodicityClass",
    "HardwarePackageProfile",
    "HardwarePreparation",
    "HardwarePreflightReport",
    "HardwareReadbackReport",
    "HardwareReadbackResult",
    "HardwareTestBuild",
    "HardwareTestBuildOutputPaths",
    "HardwareValidationStatus",
    "IdentityReply",
    "InvalidSamplePolicy",
    "MemoryTarget",
    "MemoryTargetKind",
    "MinimalProject",
    "MinimalProjectManifest",
    "ProjectAudioRecord",
    "ProjectSaveResult",
    "ProjectSourceCheck",
    "SourceStatus",
    "SourceValidationPolicy",
    "MonoConversionReport",
    "MonoPolicy",
    "MonoStrategy",
    "MultiProgram",
    "OverwritePlan",
    "PackageBuildResult",
    "PackageManifest",
    "PackageOutputPaths",
    "PackagePlan",
    "PackageRequest",
    "SoundBank",
    "SoundDestination",
    "SoundNamePolicy",
    "SoundProgram",
    "SysExMessage",
    "UserWave",
    "UserWaveAllocation",
    "UserWavetable",
    "UserWavetableDestination",
    "__version__",
    "allocate_user_waves",
    "analyze_collisions",
    "analyze_time_domain",
    "analyze_levels",
    "analyze_envelope",
    "analyze_audio_source",
    "analyze_pitch_periodicity",
    "analyze_audio_source_pitch_periodicity",
    "frequency_to_midi",
    "midi_to_frequency",
    "nearest_midi_note",
    "midi_note_name",
    "describe_frequency",
    "build_hardware_test_from_backup",
    "build_package",
    "compare_hardware_readback",
    "convert_to_mono",
    "decode_typed",
    "encode_sound_name",
    "fingerprint_file",
    "import_audio",
    "inspect_hardware_package",
    "measure_mono",
    "normalize_float_samples",
    "open_project",
    "plan_package",
    "prepare_hardware_validation",
    "save_project",
    "split_sysex_stream",
    "supported_extensions",
]
