from __future__ import annotations

from .models import OptimizationProfile, ProfileWeights


# Every vector is explicit, deterministic, and sums exactly to one.
_PROFILE_WEIGHTS: dict[OptimizationProfile, ProfileWeights] = {
    OptimizationProfile.BASS_SUB: ProfileWeights(
        time_fidelity=0.05,
        spectral_fidelity=0.05,
        phase_fidelity=0.10,
        seam_quality=0.05,
        fundamental=0.20,
        h2=0.12,
        h3=0.08,
        low_band=0.15,
        mid_band=0.03,
        high_band=0.01,
        perceptual=0.04,
        aliasing=0.04,
        ringing=0.02,
        amplitude=0.06,
    ),
    OptimizationProfile.LEAD: ProfileWeights(
        time_fidelity=0.09,
        spectral_fidelity=0.12,
        phase_fidelity=0.07,
        seam_quality=0.07,
        fundamental=0.09,
        h2=0.07,
        h3=0.06,
        low_band=0.03,
        mid_band=0.11,
        high_band=0.10,
        perceptual=0.08,
        aliasing=0.05,
        ringing=0.03,
        amplitude=0.03,
    ),
    OptimizationProfile.PAD: ProfileWeights(
        time_fidelity=0.06,
        spectral_fidelity=0.13,
        phase_fidelity=0.08,
        seam_quality=0.08,
        fundamental=0.05,
        h2=0.05,
        h3=0.04,
        low_band=0.06,
        mid_band=0.10,
        high_band=0.07,
        perceptual=0.15,
        aliasing=0.04,
        ringing=0.04,
        amplitude=0.05,
    ),
    OptimizationProfile.BELL_FM: ProfileWeights(
        time_fidelity=0.05,
        spectral_fidelity=0.18,
        phase_fidelity=0.05,
        seam_quality=0.04,
        fundamental=0.05,
        h2=0.05,
        h3=0.05,
        low_band=0.02,
        mid_band=0.10,
        high_band=0.13,
        perceptual=0.10,
        aliasing=0.10,
        ringing=0.05,
        amplitude=0.03,
    ),
    OptimizationProfile.VOCAL_CHOIR: ProfileWeights(
        time_fidelity=0.06,
        spectral_fidelity=0.16,
        phase_fidelity=0.05,
        seam_quality=0.05,
        fundamental=0.07,
        h2=0.05,
        h3=0.04,
        low_band=0.03,
        mid_band=0.16,
        high_band=0.06,
        perceptual=0.14,
        aliasing=0.05,
        ringing=0.04,
        amplitude=0.04,
    ),
    OptimizationProfile.TEXTURE: ProfileWeights(
        time_fidelity=0.05,
        spectral_fidelity=0.15,
        phase_fidelity=0.03,
        seam_quality=0.05,
        fundamental=0.02,
        h2=0.03,
        h3=0.03,
        low_band=0.04,
        mid_band=0.12,
        high_band=0.14,
        perceptual=0.15,
        aliasing=0.08,
        ringing=0.06,
        amplitude=0.05,
    ),
    OptimizationProfile.DRONE: ProfileWeights(
        time_fidelity=0.09,
        spectral_fidelity=0.11,
        phase_fidelity=0.12,
        seam_quality=0.09,
        fundamental=0.12,
        h2=0.07,
        h3=0.05,
        low_band=0.10,
        mid_band=0.05,
        high_band=0.02,
        perceptual=0.07,
        aliasing=0.03,
        ringing=0.03,
        amplitude=0.05,
    ),
    OptimizationProfile.PERCUSSIVE: ProfileWeights(
        time_fidelity=0.16,
        spectral_fidelity=0.12,
        phase_fidelity=0.04,
        seam_quality=0.10,
        fundamental=0.03,
        h2=0.03,
        h3=0.03,
        low_band=0.04,
        mid_band=0.09,
        high_band=0.13,
        perceptual=0.08,
        aliasing=0.06,
        ringing=0.06,
        amplitude=0.03,
    ),
    OptimizationProfile.EXPERIMENTAL: ProfileWeights(
        time_fidelity=0.05,
        spectral_fidelity=0.13,
        phase_fidelity=0.04,
        seam_quality=0.04,
        fundamental=0.05,
        h2=0.04,
        h3=0.04,
        low_band=0.06,
        mid_band=0.10,
        high_band=0.12,
        perceptual=0.14,
        aliasing=0.08,
        ringing=0.05,
        amplitude=0.06,
    ),
}


def weights_for_profile(profile: OptimizationProfile) -> ProfileWeights:
    return _PROFILE_WEIGHTS[OptimizationProfile(profile)]


def canonical_profile_weights() -> dict[OptimizationProfile, ProfileWeights]:
    return dict(_PROFILE_WEIGHTS)
